import 'package:flutter/material.dart';
///import 'data.dart';
///import 'tutorial1.dart';
///import 'mediaquery.dart';
///import 'listtile.dart';
///import 'stack.dart';
///import 'image.dart';
///import 'liquid.dart';
///import 'card.dart';
///import 'gridview.dart';
///import 'expanded.dart';
///import 'pageview.dart';
///import 'hero.dart';
///import 'bottomNevbar.dart';
///import 'tabbar.dart';
///import 'sliverapp.dart';
///import 'gradient.dart';
///import 'setstate.dart';
///import 'package:provider/provider.dart';
///import 'provider.dart';
///import 'setstate.dart';
///import 'imagepicker.dart';
///import 'bottomsheet.dart';
///import 'alertdialog.dart';
///import 'curvedNavigator.dart';
///import 'custom_dialog.dart';
///import 'snackbar.dart';
///import 'toast.dart';
///import 'slider.dart';
///import 'richtext.dart';
///import 'dropdown.dart';
///import 'dismiss.dart';
///import 'checkbox.dart';
///import 'crossfade.dart';
///import 'switch.dart';
///import 'animatedcontainer.dart';
///import 'expansion.dart';
///import 'tooltip.dart';
///import 'backdrop.dart';
///import 'datetime.dart';
///import 'transform.dart';
///import 'datatable.dart';

///import 'navigationrail.dart';
///import 'passeddata.dart';

import 'firebase.dart';

void main() => runApp(new MyApp());

